events {}

http {
    upstream auth_service {
        server auth-service:5001;
    }

    upstream hotel_service {
        server hotel-service:5002;
    }

    upstream room_service {
        server room-service:5003;
    }

    upstream booking_service {
        server booking-service:5004;
    }

    upstream payment_service {
        server payment-service:5005;
    }

    upstream notification_service {
        server notification-service:5006;
    }

    upstream user_service {
        server user-service:5007;
    }

    server {
        listen 80;

        location /health {
            return 200 "frontend api gateway is UP\n";
            add_header Content-Type text/plain;
        }

        location /auth/ {
            proxy_pass http://auth_service;
        }

        location /hotels {
            proxy_pass http://hotel_service;
        }

        location /rooms {
            proxy_pass http://room_service;
        }

        location /bookings {
            proxy_pass http://booking_service;
        }

        location /payments {
            proxy_pass http://payment_service;
        }

        location /notifications {
            proxy_pass http://notification_service;
        }

        location /users {
            proxy_pass http://user_service;
        }

        location / {
            return 200 "Hotel Booking API Gateway\nAvailable routes: /auth, /hotels, /rooms, /bookings, /payments, /notifications, /users\n";
            add_header Content-Type text/plain;
        }
    }
}