apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking_sre_endterm-booking-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5004
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: hotel-booking-config
                  key: DB_HOST
          readinessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5004
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: hotel-booking
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 5004
      targetPort: 5004
  type: ClusterIP