apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: booking_sre_endterm-hotel-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  namespace: hotel-booking
spec:
  selector:
    app: hotel-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP