apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-service
  namespace: hotel-booking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: room-service
  template:
    metadata:
      labels:
        app: room-service
    spec:
      containers:
        - name: room-service
          image: booking_sre_endterm-room-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          readinessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: room-service
  namespace: hotel-booking
spec:
  selector:
    app: room-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP